spring:
  application:
    name: review-ms
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      uri: ${DB_URI}
server:
  port: 8083

springdoc:
  api-docs:
    path: /api-docs
  packagesToScan: com.review.ms.controller

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka/