spring:
  application:
    name: review-ms
    data:
      mongodb:
        authentication-database: admin
        host: ${DB_HOST}
        port: ${DB_PORT}
        database: ${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

server:
  port: 8083