spring:
  application:
    name: review-ms
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      uri: ${DB_URI}
server:
  port: 8083

springdoc:
  api-docs:
    path: /api-docs
  packagesToScan: com.review.ms.controller